### ISSUE TITLE
Clarify: who should receive blame information and what information should they receive?

### ISSUE THREAD

**Issue by emergent-reasons** [cashshuffle/spec#2]
I included my recommendation as `ER` below.

Who:

- all players (`ER`)
- all but blamed
- whomever the accuser chooses for unicast

What:

- full message (`ER`)
- accuser
- accused
- blame reason

**Comment by zquestz** [comment]
So right now, the blame should go to all players unless they send it to themselves which is just for the server to see. Not sure why @clifordsymack added that option, we should probably get his input.

**Comment by emergent-reasons** [comment]
> So right now, the blame should go to all players unless they send it to themselves which is just for the server to see. Not sure why @clifordsymack added that option, we should probably get his input.

If I read the code correctly, the server allows blames to be broadcast or unicast to any player including to self. The intention of self-message is probably to vote privately. However it seems like a good point to clarify if this should be part of the spec or just an implementation concern.

I think it would be: Server SHOULD broadcast blame messages to all players in the pool regardless of player intention.

I.e. unless there is a good reason, let players know when they are blamed. It will help honest clients to improve and it will have no impact on malicious clients who would already be familiar with the source code.

**Comment by zquestz** [comment]
Yep I am in agreement. I think it makes sense to always broadcast the blames. However, I don't think the server should force any particular behavior. The clients should be sending a broadcast message, but if they decide to use unicast for some reason then we should allow it. This allows different versions of the protocol to stay consistent and keeps the server as just a dumb message proxy.
